In [1]:
#kütüphaneleri içeri aktarıyoruz
import pandas as pd 
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
#veri setini içeriye aktarıyoruz
df = pd.read_csv("sms_spam.csv")

In [15]:
vectorizer = TfidfVectorizer()
x = vectorizer.fit_transform(df.text)
print(x)

  (0, 3571)	0.14787938686701288
  (0, 8084)	0.23001892323914586
  (0, 4374)	0.326467645747019
  (0, 5958)	0.25535113536077003
  (0, 2338)	0.2528296765647095
  (0, 1316)	0.2441904570208067
  (0, 5571)	0.15603453765460987
  (0, 4114)	0.10700055412297083
  (0, 1767)	0.2758032215037706
  (0, 3655)	0.1803467768751424
  (0, 8548)	0.22083422107921832
  (0, 4501)	0.2758032215037706
  (0, 1765)	0.31164925159555484
  (0, 2061)	0.2758032215037706
  (0, 7694)	0.15552099304359127
  (0, 3615)	0.15305623970002818
  (0, 1082)	0.326467645747019
  (0, 8324)	0.182416008162686
  (1, 5538)	0.27190435673704183
  (1, 4537)	0.4083285209202484
  (1, 4342)	0.5236769406481622
  (1, 8450)	0.4316309977097208
  (1, 5567)	0.5466195966483365
  (2, 4114)	0.0790778808416933
  (2, 3373)	0.11311495706056472
  :	:
  (5572, 4245)	0.12207880845408346
  (5572, 8371)	0.18730428198312823
  (5572, 1097)	0.11225067656334997
  (5572, 4642)	0.1595487883020045
  (5572, 7089)	0.18433418559699824
  (5572, 3323)	0.12146432831326853
  

In [16]:
#kelime kümesini inceliyoruz
feature_names = vectorizer.get_feature_names_out()

In [17]:
# vektor temsilini incele 
vector_temsili = x.toarray()
print(vector_temsili)

df_tfidf = pd.DataFrame(vector_temsili, columns=feature_names)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [18]:
# ortalama tf idf degerlerine bakalim 
tf_idf = df_tfidf.mean(axis=0)
print(tf_idf)

00              0.000402
000             0.001161
000pes          0.000042
008704050406    0.000094
0089            0.000045
                  ...   
zouk            0.000049
zyada           0.000029
èn              0.000033
ú1              0.000040
〨ud             0.000055
Length: 8713, dtype: float64
